name: End-to-end Tests

on:
  workflow_dispatch:
    inputs:
      pull_request_id:
        description: "Pull Request ID"
        required: false
        default: ""
      sha:
        description: "GitHub SHA"
        required: false
        default: ""

jobs:
  initialize:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    outputs:
      pr_git_sha: ${{ steps.set_pr_git_sha.outputs.pr_git_sha }}

    steps:
      # For non-fork PRs
      - uses: actions/checkout@v2
        if: ${{ github.event.inputs.pull_request_id == '' }}
        with:
          ref: ${{ github.event.inputs.sha || github.ref }}

      # For manually run PRs
      - name: Initialize empty git repository
        if: ${{ github.event.inputs.pull_request_id != '' }}
        run: git init --initial-branch serverless-next-js-placeholder

      - name: Checkout pull request
        if: ${{ github.event.inputs.pull_request_id != '' }}
        uses: dawidd6/action-checkout-pr@v1
        with:
          pr: ${{ github.event.inputs.pull_request_id }}

      - name: Set pull request's git SHA
        id: set_pr_git_sha
        if: ${{ github.event.inputs.pull_request_id != '' }}
        run: |
          echo "PR_GIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "::set-output name=pr_git_sha::$(git rev-parse HEAD)"
      - name: Mark end-to-end tests as pending with run URL
        # For manual runs (e.g for fork PRs) don't update commit status as there won't be permissions to do so
        if: ${{ github.event.inputs.pull_request_id == '' }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: "End-to-end Tests"
          description: "Waiting for end-to-end tests to pass"
          state: "pending"
          sha: ${{ steps.set_pr_git_sha.outputs.pr_git_sha || github.event.inputs.sha || github.sha }}
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Wait for existing workflow to complete before e2e tests
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 30
          same-branch-only: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-e2e-tests:
    needs: [initialize]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
        app:
          - next-app

    steps:
      # For non-fork PRs
      - uses: actions/checkout@v2
        if: ${{ github.event.inputs.pull_request_id == '' }}
        with:
          ref: ${{ github.event.inputs.sha || github.ref }}

      # For manually run PRs
      - name: Initialize empty git repository
        if: ${{ github.event.inputs.pull_request_id != '' }}
        run: git init --initial-branch serverless-next-js-placeholder

      - name: Checkout pull request
        if: ${{ github.event.inputs.pull_request_id != '' }}
        uses: dawidd6/action-checkout-pr@v1
        with:
          pr: ${{ github.event.inputs.pull_request_id }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Yarn
        uses: c-hive/gha-yarn-cache@v2

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Run yarn build
        run: yarn build

      - name: Wait for existing workflow to complete before e2e tests
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 30
          same-branch-only: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run e2e tests
        working-directory: tests/e2e/${{ matrix.app }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_AT }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ST }}
          AWS_DEFAULT_REGION: eu-north-1
          WAIT_TIMEOUT: 900
          CYPRESS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed for testing external rewrites to GitHub API without getting throttled
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          yarn install --frozen-lockfile
          yarn deploy
          yarn e2e:ci
          yarn destroy

        timeout-minutes: 30 # In case something goes wrong
      
      - name: Mark end-to-end tests as failed
        # For manual runs (e.g for fork PRs) don't update commit status as there won't be permissions to do so
        if: ${{ failure() && github.event.inputs.pull_request_id == '' }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: "End-to-end Tests"
          description: "End-to-end tests have failed"
          state: "failure"
          sha: ${{ needs.initialize.outputs.pr_git_sha || github.event.inputs.sha || github.sha }}
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

